# Generated by Django 3.2.12 on 2022-02-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='days',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='days_practiced',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
