# Generated by Django 3.2.12 on 2022-02-23 08:30

import apps.assignments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20220223_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf/', validators=[apps.assignments.utils.validate_pdf_extension]),
        ),
    ]
