# Generated by Django 3.2.12 on 2022-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pdf',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
